name: neushub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  bloc: ^9.0.0
  shared_preferences: ^2.5.1
  ionicons: ^0.2.2
  http: ^1.3.0
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: rubik
      fonts:
      - asset: fonts/Rubik-Regular.ttf

    # icons
    - family: icons
      fonts:
       - asset: fonts/icons/icons.ttf
    - family: offline
      fonts:
        - asset: fonts/icons/offline.ttf
    - family: sign
      fonts:
        - asset: fonts/icons/sign.ttf

  assets:
    - assets/images/main.png
    - assets/images/offline_background.png
    - assets/images/sign.png
    - assets/images/about_owner.png
    - assets/images/about_finder.png
    - assets/images/about_magic.png

  uses-material-design: true
