name: neushub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  bloc: ^9.0.0
  shared_preferences: ^2.5.1
  ionicons: ^0.2.2
  http: ^1.3.0
  flutter_bloc: ^9.0.0
  path_provider: ^2.1.5
  go_router: ^14.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "neushub_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  fonts:
    - family: rubik
      fonts:
      - asset: fonts/Rubik-Regular.ttf

    # icons
    - family: icons
      fonts:
       - asset: fonts/icons/icons.ttf
    - family: offline
      fonts:
        - asset: fonts/icons/offline.ttf
    - family: sign
      fonts:
        - asset: fonts/icons/sign.ttf

  assets:
    - assets/images/main.png
    - assets/images/offline_background.png
    - assets/images/sign.png
    - assets/images/about_owner.png
    - assets/images/about_finder.png
    - assets/images/about_magic.png

  uses-material-design: true
